/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesSurMesureRouteImport } from './routes/services-sur-mesure'
import { Route as LocationVehiculesRouteImport } from './routes/location-vehicules'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as DemenagementRouteImport } from './routes/demenagement'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PaiementSuccesRouteImport } from './routes/paiement.succes'
import { Route as PaiementAnnuleRouteImport } from './routes/paiement.annule'
import { Route as LocationVehiculesVehicleIdRouteImport } from './routes/location-vehicules_.$vehicleId'
import { Route as EvaluerTokenRouteImport } from './routes/evaluer.$token'
import { Route as ClientSupportRouteImport } from './routes/client.support'
import { Route as ClientReservationsRouteImport } from './routes/client.reservations'
import { Route as AdminVehiculesRouteImport } from './routes/admin.vehicules'
import { Route as AdminUtilisateursRouteImport } from './routes/admin.utilisateurs'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminRapportsRouteImport } from './routes/admin.rapports'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminChauffeursRouteImport } from './routes/admin.chauffeurs'

const ServicesSurMesureRoute = ServicesSurMesureRouteImport.update({
  id: '/services-sur-mesure',
  path: '/services-sur-mesure',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationVehiculesRoute = LocationVehiculesRouteImport.update({
  id: '/location-vehicules',
  path: '/location-vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DemenagementRoute = DemenagementRouteImport.update({
  id: '/demenagement',
  path: '/demenagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PaiementSuccesRoute = PaiementSuccesRouteImport.update({
  id: '/paiement/succes',
  path: '/paiement/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementAnnuleRoute = PaiementAnnuleRouteImport.update({
  id: '/paiement/annule',
  path: '/paiement/annule',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationVehiculesVehicleIdRoute =
  LocationVehiculesVehicleIdRouteImport.update({
    id: '/location-vehicules_/$vehicleId',
    path: '/location-vehicules/$vehicleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvaluerTokenRoute = EvaluerTokenRouteImport.update({
  id: '/evaluer/$token',
  path: '/evaluer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSupportRoute = ClientSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ClientRoute,
} as any)
const ClientReservationsRoute = ClientReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => ClientRoute,
} as any)
const AdminVehiculesRoute = AdminVehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtilisateursRoute = AdminUtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRapportsRoute = AdminRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChauffeursRoute = AdminChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/demenagement': typeof DemenagementRoute
  '/driver': typeof DriverRouteWithChildren
  '/location-vehicules': typeof LocationVehiculesRoute
  '/services-sur-mesure': typeof ServicesSurMesureRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/client/support': typeof ClientSupportRoute
  '/evaluer/$token': typeof EvaluerTokenRoute
  '/location-vehicules/$vehicleId': typeof LocationVehiculesVehicleIdRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/demenagement': typeof DemenagementRoute
  '/location-vehicules': typeof LocationVehiculesRoute
  '/services-sur-mesure': typeof ServicesSurMesureRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/client/support': typeof ClientSupportRoute
  '/evaluer/$token': typeof EvaluerTokenRoute
  '/location-vehicules/$vehicleId': typeof LocationVehiculesVehicleIdRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/demenagement': typeof DemenagementRoute
  '/driver': typeof DriverRouteWithChildren
  '/location-vehicules': typeof LocationVehiculesRoute
  '/services-sur-mesure': typeof ServicesSurMesureRoute
  '/admin/chauffeurs': typeof AdminChauffeursRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/utilisateurs': typeof AdminUtilisateursRoute
  '/admin/vehicules': typeof AdminVehiculesRoute
  '/client/reservations': typeof ClientReservationsRoute
  '/client/support': typeof ClientSupportRoute
  '/evaluer/$token': typeof EvaluerTokenRoute
  '/location-vehicules_/$vehicleId': typeof LocationVehiculesVehicleIdRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/connexion'
    | '/demenagement'
    | '/driver'
    | '/location-vehicules'
    | '/services-sur-mesure'
    | '/admin/chauffeurs'
    | '/admin/clients'
    | '/admin/missions'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/utilisateurs'
    | '/admin/vehicules'
    | '/client/reservations'
    | '/client/support'
    | '/evaluer/$token'
    | '/location-vehicules/$vehicleId'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/admin/'
    | '/client/'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/demenagement'
    | '/location-vehicules'
    | '/services-sur-mesure'
    | '/admin/chauffeurs'
    | '/admin/clients'
    | '/admin/missions'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/utilisateurs'
    | '/admin/vehicules'
    | '/client/reservations'
    | '/client/support'
    | '/evaluer/$token'
    | '/location-vehicules/$vehicleId'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/admin'
    | '/client'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/connexion'
    | '/demenagement'
    | '/driver'
    | '/location-vehicules'
    | '/services-sur-mesure'
    | '/admin/chauffeurs'
    | '/admin/clients'
    | '/admin/missions'
    | '/admin/parametres'
    | '/admin/rapports'
    | '/admin/reservations'
    | '/admin/utilisateurs'
    | '/admin/vehicules'
    | '/client/reservations'
    | '/client/support'
    | '/evaluer/$token'
    | '/location-vehicules_/$vehicleId'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/admin/'
    | '/client/'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  DemenagementRoute: typeof DemenagementRoute
  DriverRoute: typeof DriverRouteWithChildren
  LocationVehiculesRoute: typeof LocationVehiculesRoute
  ServicesSurMesureRoute: typeof ServicesSurMesureRoute
  EvaluerTokenRoute: typeof EvaluerTokenRoute
  LocationVehiculesVehicleIdRoute: typeof LocationVehiculesVehicleIdRoute
  PaiementAnnuleRoute: typeof PaiementAnnuleRoute
  PaiementSuccesRoute: typeof PaiementSuccesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services-sur-mesure': {
      id: '/services-sur-mesure'
      path: '/services-sur-mesure'
      fullPath: '/services-sur-mesure'
      preLoaderRoute: typeof ServicesSurMesureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-vehicules': {
      id: '/location-vehicules'
      path: '/location-vehicules'
      fullPath: '/location-vehicules'
      preLoaderRoute: typeof LocationVehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demenagement': {
      id: '/demenagement'
      path: '/demenagement'
      fullPath: '/demenagement'
      preLoaderRoute: typeof DemenagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/paiement/succes': {
      id: '/paiement/succes'
      path: '/paiement/succes'
      fullPath: '/paiement/succes'
      preLoaderRoute: typeof PaiementSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/annule': {
      id: '/paiement/annule'
      path: '/paiement/annule'
      fullPath: '/paiement/annule'
      preLoaderRoute: typeof PaiementAnnuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-vehicules_/$vehicleId': {
      id: '/location-vehicules_/$vehicleId'
      path: '/location-vehicules/$vehicleId'
      fullPath: '/location-vehicules/$vehicleId'
      preLoaderRoute: typeof LocationVehiculesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluer/$token': {
      id: '/evaluer/$token'
      path: '/evaluer/$token'
      fullPath: '/evaluer/$token'
      preLoaderRoute: typeof EvaluerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/support': {
      id: '/client/support'
      path: '/support'
      fullPath: '/client/support'
      preLoaderRoute: typeof ClientSupportRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/reservations': {
      id: '/client/reservations'
      path: '/reservations'
      fullPath: '/client/reservations'
      preLoaderRoute: typeof ClientReservationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/vehicules': {
      id: '/admin/vehicules'
      path: '/vehicules'
      fullPath: '/admin/vehicules'
      preLoaderRoute: typeof AdminVehiculesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utilisateurs': {
      id: '/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AdminUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapports': {
      id: '/admin/rapports'
      path: '/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AdminRapportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chauffeurs': {
      id: '/admin/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/admin/chauffeurs'
      preLoaderRoute: typeof AdminChauffeursRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChauffeursRoute: typeof AdminChauffeursRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminMissionsRoute: typeof AdminMissionsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminRapportsRoute: typeof AdminRapportsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminUtilisateursRoute: typeof AdminUtilisateursRoute
  AdminVehiculesRoute: typeof AdminVehiculesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChauffeursRoute: AdminChauffeursRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminMissionsRoute: AdminMissionsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminRapportsRoute: AdminRapportsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminUtilisateursRoute: AdminUtilisateursRoute,
  AdminVehiculesRoute: AdminVehiculesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientReservationsRoute: typeof ClientReservationsRoute
  ClientSupportRoute: typeof ClientSupportRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientReservationsRoute: ClientReservationsRoute,
  ClientSupportRoute: ClientSupportRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DriverRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  DemenagementRoute: DemenagementRoute,
  DriverRoute: DriverRouteWithChildren,
  LocationVehiculesRoute: LocationVehiculesRoute,
  ServicesSurMesureRoute: ServicesSurMesureRoute,
  EvaluerTokenRoute: EvaluerTokenRoute,
  LocationVehiculesVehicleIdRoute: LocationVehiculesVehicleIdRoute,
  PaiementAnnuleRoute: PaiementAnnuleRoute,
  PaiementSuccesRoute: PaiementSuccesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
